src/Entity/Domain.php
<?php

namespace App\Entity;

use App\Repository\DomainRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DomainRepository::class)]
class Domain
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'domains')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $icon_url = null;

    #[ORM\OneToMany(mappedBy: 'domain', targetEntity: Station::class)]
    private Collection $stations;

    public function __construct()
    {
        $this->stations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIconUrl(): ?string
    {
        return $this->icon_url;
    }

    public function setIconUrl(?string $icon_url): self
    {
        $this->icon_url = $icon_url;

        return $this;
    }

    /**
     * @return Collection<int, Station>
     */
    public function getStations(): Collection
    {
        return $this->stations;
    }

    public function addStation(Station $station): self
    {
        if (!$this->stations->contains($station)) {
            $this->stations->add($station);
            $station->setDomain($this);
        }

        return $this;
    }

    public function removeStation(Station $station): self
    {
        if ($this->stations->removeElement($station)) {
            // set the owning side to null (unless already changed)
            if ($station->getDomain() === $this) {
                $station->setDomain(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }
}

src/Controller/DomainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\DomainRepository;
use App\Repository\StationRepository;
use Symfony\Component\Routing\Annotation\Route;

class DomainController extends AbstractController
{
    // ...

    #[Route('/domain/{id}', name: 'app_domain_show')]
    public function show(int $id, DomainRepository $domainRepository, StationRepository $StationRepository): Response
    {
      
        $domain = $domainRepository->find($id);

        if (!$domain) {
            throw $this->createNotFoundException('Le domaine avec l\'ID ' . $id . ' n\'existe pas');
        }
        $stations = $domain->getStations();

        return $this->render('domain/show.html.twig', [
            'domain' => $domain,
            'stations' => $stations
        ]);
    }
}

templates/domain/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ domain.name }}{% endblock %}

{% block body %}
<style>
    body {
        background-color: #FAFAFA;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .example-wrapper {
        padding: 100px 0;
        width: 80%;
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        grid-template-rows: repeat(4, 1fr);
        grid-column-gap: 2em;
        grid-row-gap: 2em;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }

    #icon {
        object-fit: fill;
        position: absolute;
        width: 20%;
        height: 20%;
        z-index: 3;
        top: 3%;
        left: 5%;
    }
    #domain-icon {
        width: 100px;
    }

    .domaine {
        width: 100%;
        height: 100vh;
        display: flex;
        flex-direction: row;
    }

    .domaine .content {
        width: 50%;
        height: 100%;
        padding: 10em 4.5em;
    }

    .domaine .content h1 {
        font-size: 4em;
    }

    .domaine .content p {
        font-size: 1.5em;
        padding-top: 2em;
    }

    .domaine .content-img {
        width: 50%;
        height: 100%;
    }

    .domaine .content-img img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    .card-station {
        position: relative;
        width: 100%;
        height: 350px;
    }

    .card-station img {
        position: absolute;
        width: 100%;
        height: 100%;
        object-fit: cover;
        z-index: 1;
    }

    .card-station .content-station {
        padding: 1em;
        position: absolute;
        display: flex;
        flex-direction: column;
        justify-content: space-around;
        z-index: 2;
        top: 40%;
        width: 100%;
        height: 60%;
        left: 0%;
        background: #FFFFFF;
        box-shadow: -10px 10px 20px rgba(0, 0, 0, 0.25);
    }

    .card-station h3 {
        z-index: 2;
        top: 10%;
        left: 30%;
        position: absolute;
        font-family: 'Oswald';
        font-style: normal;
        font-weight: 400;
        font-size: 1.5em;
        padding-bottom: 2em;
        line-height: 30px;

        color: #FFFFFF;

        text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    .card-station .content-station p {
        display: -webkit-box;
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
        -webkit-line-clamp: 3;
        /* nombre maximum de lignes */
        line-clamp: 3;
        font-size: 1em;

    }

    .card-station .content-station a {
        text-decoration: none;
        width: 100%;
        text-align: right;
        padding: 0.5em 1.5em;
        font-size: 1em;
        color: rgb(0, 88, 252);
    }

    /* responsive ordi portable */
    @media (max-width: 1024px) {
        .example-wrapper {
            grid-template-columns: repeat(1, 1fr);
            grid-template-rows: repeat(4, 1fr);
        }
    }

    /* responsive tablette */
    @media (max-width: 768px) {
        .domaine {
            position: relative;
            width: 100%;
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        .domaine .content {
            position: absolute;
            top: 20%;
            left: 15%;
            right: 15%;
            width: 70%;
            height: 50%;
            padding: 4em 4.5em;
            background-color: rgba(255, 255, 255, 0.746);
        }

        .domaine .content h1 {
            font-size: 3em;
        }

        .domaine .content p {
            font-size: 1.3em;
            padding-top: 2em;
        }

        .domaine .content-img {
            width: 100%;
            height: 100%;
        }
    }

    @media (max-width: 650px) {

        .domaine .content {
            position: absolute;
            top: 20%;
            left: 15%;
            right: 15%;
            width: 70%;
            height: 50%;
            padding: 2em 1.5em;
            background-color: rgba(255, 255, 255, 0.746);
        }

        .domaine .content h1 {
            font-size: 2em;
        }

        .domaine .content p {
            font-size: 1.3em;
            padding-top: 1.3em;
        }

        .domaine .content-img {
            width: 100%;
            height: 100%;
        }
    }
</style>

<div class="domaine">
    <div class="content">
        <img id="domain-icon" src="{{ asset('uploads/icons/' ~ domain.iconUrl ) }}" alt="">
        <h1> {{ domain.name }} </h1>
        <p>{{ domain.description }} </p>
    </div>
    <div class="content-img">
        <img src="{{ asset('assets/img/Domaines_background_ED.jpg')}}" alt="">
    </div>
</div>
<div class="example-wrapper">
    {% for station in stations %}

    <div class="card-station">
        <img src="{{ asset('assets/img/Domaines_background_ED.jpg')}}" alt="">
        <img id="icon" src="{{ asset('/uploads/icons/' ~ station.iconUrl) }}">
        <h3> {{ station.name }} </h3>
        <div class="content-station">
            <p> {{ station.description }} </p>
            <a href="{{ path('app_station_show', {'id': station.id}) }}">Voir plus</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}