src/Entity/Trail.php
<?php

namespace App\Entity;

use App\Repository\TrailRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrailRepository::class)]
class Trail
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $total_duration = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'trail_id', targetEntity: LinkTrail::class)]
    private Collection $linkTrails;

    #[ORM\ManyToOne(inversedBy: 'trails')]
    #[ORM\JoinColumn(nullable: false)]
    private ?user $owner = null;

    #[ORM\Column]
    private ?bool $is_completed = null;

    public function __construct()
    {
        $this->linkTrails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTotalDuration(): ?\DateTimeInterface
    {
        return $this->total_duration;
    }

    public function setTotalDuration(\DateTimeInterface $total_duration): self
    {
        $this->total_duration = $total_duration;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, LinkTrail>
     */
    public function getLinkTrails(): Collection
    {
        return $this->linkTrails;
    }

    public function addLinkTrail(LinkTrail $linkTrail): self
    {
        if (!$this->linkTrails->contains($linkTrail)) {
            $this->linkTrails->add($linkTrail);
            $linkTrail->setTrailId($this);
        }

        return $this;
    }

    public function removeLinkTrail(LinkTrail $linkTrail): self
    {
        if ($this->linkTrails->removeElement($linkTrail)) {
            // set the owning side to null (unless already changed)
            if ($linkTrail->getTrailId() === $this) {
                $linkTrail->setTrailId(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?user
    {
        return $this->owner;
    }

    public function setOwner(?user $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function isIsCompleted(): ?bool
    {
        return $this->is_completed;
    }

    public function setIsCompleted(bool $is_completed): self
    {
        $this->is_completed = $is_completed;

        return $this;
    }
}

src/Controller/MyTrailsController.php
<?php

namespace App\Controller;

use App\Entity\LinkTrail;
use App\Entity\Trail;
use App\Controller\SecurityController;
use App\Repository\LinkTrailRepository;
use App\Repository\TrailRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MyTrailsController extends AbstractController
{
    private $security;
    public function __construct(SecurityController $security)
    {
        $this->security = $security;
    }


    #[Route('/my/trails', name: 'app_my_trails')]
    public function index(
        TrailRepository $TrailRepository,
        LinkTrailRepository $LinkTrail,
    ): Response
    {
        $user = $this->security->getUser();

        // Get all my trails
        $allMyTrails = $TrailRepository->findBy(['owner' => $user->getId(), 'is_completed' => true]);

        $allStartTrails = [];
        foreach($allMyTrails as $trail){
            $startTrail = $LinkTrail->findBy(['trail_id' => $trail->getId()],['id' => 'ASC'],3);
            $allStartTrails[] = $startTrail;
        }

        // dd($allStartTrails);

        return $this->render('my_trails/index.html.twig', [
            'controller_name' => 'MyTrailsController',
            'Trails' => $allMyTrails,
            'trailsStart' => $allStartTrails
        ]);
    }
}

templates/my_trails/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MyTrailsController!{% endblock %}

{% block body %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap');
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        color : black;
        font-family: 'Oswald', sans-serif;
    }

    h1{
        text-align: center;
        font-size: 42px;
        margin: 10px;
        color: white;
    }

    body {
        background-image: url("../backgroundTrail.jpg");
        background-size: 150%;
        background-repeat: no-repeat;
    }

    .showParcours{
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 80%;
        margin: auto;
        margin-bottom: 20px;
    }


    .allMyTrails {
        display: flex;
        flex-direction: column;
        justify-content: space-around;
        width: 85%;
        border-radius: 16px;
        background-color: rgba(255, 255, 255, 0.6);
        backdrop-filter: blur(2px);
        padding: 20px;
    }

    .oneTrail{
        margin: auto;
        text-align:center;
        margin-top: 20px;
    }

    .oneTrail > div{
        display:flex;
        flex-direction: column;
        margin-top: 8px;
        gap: 5px;
    }

    .apercu{
        display:flex;
        flex-direction: column;
    }


</style>

<section class="showParcours">
    <h1>Mes parcours créés</h1>
    <div class="allMyTrails">
        {% for Trail in Trails %}
            {% set i = loop.index %}
            <div class="oneTrail">
                <h2>{{Trail.name}}</h2>
                <span> Temps total : {{Trail.totalDuration|date("i:s")}}</span>
                <div>
                    <b>Aperçu</b>
                    <div class="apercu">
                        {% for element in trailsStart[i - 1] %}
                            {% if element.liftid == null %}
                                <span>{{element.slopeid.name}}</span>
                            {% else %}
                                <span>{{element.liftid.name}}</span>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    <div>
</section>
{% endblock %}