src/Entity/Slope.php
<?php

namespace App\Entity;

use App\Repository\SlopeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SlopeRepository::class)]
class Slope
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'lifts')]
	#[ORM\JoinColumn(nullable: false)]
	private ?Station $station = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $difficulty = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $first_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $last_hour = null;

    #[ORM\Column(nullable: true)]
    private ?bool $exception = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $exception_message = null;


    #[ORM\OneToMany(mappedBy: 'slope_id', targetEntity: LinkTrail::class)]
    private Collection $linkTrails;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $duration = null;

    public function __construct()
    {
        $this->linkTrails = new ArrayCollection();
    }

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $Peak_Hour = null;

    #[ORM\Column(nullable: true)]
    private ?int $snow_quality = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStation(): ?Station
    {
        return $this->station;
    }

    public function setStation(?Station $station): self
    {
        $this->station = $station;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(int $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getFirstHour(): ?\DateTimeInterface
    {
        return $this->first_hour;
    }

    public function setFirstHour(\DateTimeInterface $first_hour): self
    {
        $this->first_hour = $first_hour;

        return $this;
    }

    public function getLastHour(): ?\DateTimeInterface
    {
        return $this->last_hour;
    }

    public function setLastHour(\DateTimeInterface $last_hour): self
    {
        $this->last_hour = $last_hour;

        return $this;
    }

    public function isException(): ?bool
    {
        return $this->exception;
    }

    public function setException(?bool $exception): self
    {
        $this->exception = $exception;

        return $this;
    }

    public function getExceptionMessage(): ?string
    {
        return $this->exception_message;
    }

    public function setExceptionMessage(?string $exception_message): self
    {
        $this->exception_message = $exception_message;

        return $this;
    }


    /**
     * @return Collection<int, LinkTrail>
     */
    public function getLinkTrails(): Collection
    {
        return $this->linkTrails;
    }

    public function addLinkTrail(LinkTrail $linkTrail): self
    {
        if (!$this->linkTrails->contains($linkTrail)) {
            $this->linkTrails->add($linkTrail);
            $linkTrail->setSlopeId($this);
        }
    }

    public function getPeakHour(): ?\DateTimeInterface
    {
        return $this->Peak_Hour;
    }

    public function setPeakHour(?\DateTimeInterface $Peak_Hour): self
    {
        $this->Peak_Hour = $Peak_Hour;

        return $this;
    }


    public function removeLinkTrail(LinkTrail $linkTrail): self
    {
        if ($this->linkTrails->removeElement($linkTrail)) {
            // set the owning side to null (unless already changed)
            if ($linkTrail->getSlopeId() === $this) {
                $linkTrail->setSlopeId(null);
            }
        }

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->duration;
    }

    public function setDuration(\DateTimeInterface $duration): self
    {
        $this->duration = $duration;

        return $this;
    }
    public function getSnowQuality(): ?int
    {
        return $this->snow_quality;
    }

    public function setSnowQuality(?int $snow_quality): self
    {
        $this->snow_quality = $snow_quality;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/SlopeType.php
<?php

namespace App\Form;

use App\Entity\Slope;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SlopeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('difficulty')
            ->add('first_hour')
            ->add('last_hour')
            ->add('exception')
            ->add('exception_message')
            ->add('Peak_Hour')
            ->add('snow_quality')
            ->add('station')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Slope::class,
        ]);
    }
}

src/Controller/SlopeController.php
<?php

namespace App\Controller;


use App\Entity\Slope;
use App\Form\SlopeType;
use App\Repository\SlopeRepository;
use App\Entity\Lift;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/slope')]
class SlopeController extends AbstractController
{

    /**
     * @throws Exception
     */
    #[Route('/{id}', name: 'app_slope_show')]
    public function show(Slope $slope): Response{


        $heureActuelle = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $heureOuverture = \DateTime::createFromFormat('H:i:s', $slope->getFirstHour()->format('H:i:s'));
        $heureFermeture = \DateTime::createFromFormat('H:i:s', $slope->getLastHour()->format('H:i:s'));

        if ($heureActuelle < $heureOuverture){
            $diff = $heureOuverture->diff($heureActuelle);
            $tempsRestant = $diff->format('%H heures %i minutes');
            $messageTxt = "La piste est fermée pour le moment. Elle ouvrira dans " ;
            $messageValue =  $tempsRestant;

        } elseif ($heureActuelle <= $heureFermeture){
            $diff = $heureFermeture->diff($heureActuelle);
            $tempsRestant = $diff->format('%H heures %i minutes');
            $messageTxt = "La piste est ouverte. Elle fermera dans " ;

            $messageValue =  $tempsRestant;
        } else {
            $diff = $heureActuelle->diff($heureFermeture);
            $tempsRestant = $diff->format('%H heures %i minutes');
            $messageTxt = "La piste est fermée depuis " ;

            $messageValue =  $tempsRestant;
        }


        $station_id = $slope->getStation()->getId();

        return $this->render('slope/show.html.twig', [
            'slope' => $slope,
            'message' => $messageTxt,
            "messageValue" => $messageValue,
            'station_id' => $station_id,
            'exception_message'=> $slope->getExceptionMessage(),

        ]);
    }
}

templates/slope/_delete_form.html.twig
<form method="post" action="{{ path('app_slope_delete', {'id': slope.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ slope.id) }}">
    <button class="btn">Delete</button>
</form>

templates/slope/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/slope/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Slope{% endblock %}

{% block body %}
    <h1>Edit Slope</h1>

    {{ include('slope/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_slope_index') }}">back to list</a>

    {{ include('slope/_delete_form.html.twig') }}
{% endblock %}

templates/slope/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Slope index{% endblock %}

{% block body %}
    <a href="{{ path('app_slope_new') }}">Create new</a>
{% endblock %}

templates/slope/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Slope{% endblock %}

{% block body %}
    <h1>Create new Slope</h1>

    {{ include('slope/_form.html.twig') }}

    <a href="{{ path('app_slope_index') }}">back to list</a>
{% endblock %}

templates/slope/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}{{ slope.name }}
{% endblock %}

{% block body %}
    <div class="container">


        <section class="lift-first-section">

            <h1 class="card-name-test"> {{ slope.name }}! </h1>
            <a class="btn-station" href="{{ path('app_station_show', {'id': slope.station.id}) }}">Accedez aux infos de la
                station</a>


        </section>
        <section class="lift-data-section">


            {% if slope.exception == true %}
                <div class="closed-div">
                    <h1 class="closed"> fermé </h1>
                    <h2 class="exeption_message"> {{ exception_message }} </h2>

                </div>

            {% else %}
                {% if message == "La piste est ouverte. Elle fermera dans " %}
                    <div>
                        <h2 class="green-message">{{ message }} : </h2>
                        <h2>{{ messageValue }}</h2>
                    </div>
                {% else %}
                    <div>
                        <h2 class="red-message">{{ message }} : </h2>
                        <h2>{{ messageValue }}</h2>
                    </div>
                {% endif %}
                <div>
                    <h2> Qualité de la neige :</h2>

                    <h2>{{ slope.snowquality}} / 5</h2>
                </div>

            {% endif %}


        </section>

    </div>

    <div class="container">
        <table>
            <thead>
            <tr>
                <th>Difficulté</th>
                <th>Heure d'ouverture</th>
                <th>Heure de fermeture</th>
                <th>Heure de pointe</th>
                <th>Temps moyen de descente</th>
                <th>Type de piste</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ slope.difficulty }}</td>
                <td>{{ slope.firstHour|date('H:m') }}</td>
                <td>{{ slope.lastHour|date('H:m') }}</td>
                <td>{{ slope.peakHour|date('H:m') }}</td>
                <td>{{ slope.duration|date('m:s') }}</td>
                <td>{{ slope.type }}</td>
            </tbody>
        </table>
    </div>





    <style>
        .green-message {
            color: green;

        }
        .red-message {
            color: red;


        }
        .closed {
            text-transform: uppercase;
            color: red;
            margin-bottom: 150px;
            font-weight: bold;
            font-size: 50px;
            width: 100%;

            border: 4px double red;
            text-align: center;

        }

        .closed-div {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            justify-content: space-around;


        }

        .exeption_message {
            color: black;
            margin-bottom: 150px;
            font-weight: bold;
            font-size: 50px;
            background-color: white;
            opacity: 0.8;

        }

        .container {
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;
            align-items: center;

            height: 70vh;
            width: 100vw;

        }

        .lift-first-section {

            height: 70vh;
            width: 40%;
            background: url("/assets/images/signup-background-img.png");

            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;


            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            justify-content: space-around;

        }

        body {

        }

        .card-name-test {
            color: white;


            padding: 10px;
            border-radius: 5px;
            text-align: center;
            font-size: 75px;

        }

        .btn-station {
            background-color: #000000;
            color: #FFFFFF;
            opacity: 0.9;
            border: none;
            border-radius: 4px;
            padding: 12px 0;
            width: 150px;
            font-size: 16px;
            font-weight: 500;
            cursor: pointer;
            text-decoration: none;
            text-align: center;
        }

        .btn-station:hover {
            background-color: #0054D2;
        }

        .lift-data-section {
            padding: 40px 0;
            height: 70vh;
            width: 40%;


            background: url("/assets/img/activitée/ski-de-fond.jpg");

            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;


            display: flex;
            flex-direction: column;

            align-items: center;
            justify-content: space-between;


        }


        @media only screen and (max-width : 1224px){
            .container {
                display: flex;
                flex-direction: column;
                justify-content: space-evenly;
                align-items: center;

                height: 140vh;
                width: 100vw;
            }
            .lift-data-section {
                margin-top: 50px;
                padding: 40px 0;
                height: 70vh;
                width: 70%;
                background-size: cover;
                background: url("/assets/img/activitée/ski-de-fond.jpg") no-repeat center center;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: space-between;
            }
            .lift-first-section {
                margin-top: 20px;
                height: 70vh;
                width: 70%;
            }
        }

        /* Style pour le tableau */
        table {
            border-collapse: collapse;
            width: 80%;
            margin: 0 auto;
            border: 1px solid #ddd;
            font-size: 18px;
        }

        th, td {
            text-align: left;
            padding: 16px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2
        }



    </style>

{% endblock %}